name: Dev Testing 🔎

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" > .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env
          
          # For debugging: show what we wrote to .env (without revealing secrets)
          echo ".env file content:"
          cat .env | sed 's/=.*/=***/' # Masks the values for security
        

      - name: Build and Run Container
        run: |
          sudo docker compose --profile dev up --build --detach
      
      - name: Wait for application and check health
        run: |
          echo "Waiting for application to start..."
          # Wait for container to be running first
          timeout 30 bash -c 'until sudo docker compose ps | grep pacmusic-dev | grep -q "running"; do echo "Waiting for container..."; sleep 2; done'
          
          # Then wait for the application to respond (even with 500)
          timeout 30 bash -c 'until curl -s http://localhost:5000 >/dev/null; do echo "Waiting for application..."; sleep 2; done'
          
      - name: Debug - Get detailed logs
        run: |
          echo "=== Container Status ==="
          sudo docker compose ps -a
          
          echo "=== Application Logs ==="
          sudo docker compose logs pacmusic-dev --tail=50
          
          echo "=== Try to get error details ==="
          # Sometimes curl can get more details even with 500 error
          curl -v http://localhost:5000 || true
          
          echo "=== Check if we can see the error response ==="
          curl -s http://localhost:5000 | head -20 || true

      - name: Test if basic endpoint works
        run: |
          # This will fail if we get 500, but we want to see the test results
          curl -f http://localhost:5000